# GPT Companion default profile
# Do not change property names in this file. Do not delete any property.
# Create as many custom profiles as you like and pick the specific properties to overwrite.
# All props are OPTIONAL unless marked as MANDATORY
[settings]
# MANDATORY, name to display in model selection
name  = "Default"
# Model names taken from https://platform.openai.com/playground
# ONLY chat models are supported. The legacy completion API is not supported.
models = [ 'gpt-4.1', 'gpt-4.1-mini', 'o3-mini']
# give a general instruction to the model.
instruction = "Your task is to improve the text. Be precise and concise. Do not add anything, just present the modified text."
# GPT temperature
temperature = 0.7
# default value for max number of tokens in response
max_tokens = 500

# MANDATORY key-value pairs of action names, which are displayed as choices in the UI, and action prompts, which are put in front
# of the input text. The first entry is the default.
# You can use the placeholder $text anywhere in the prompt.
[actions]
"Pass-through"= "$text"
"Summarize" =  "rewrite summarized:\n"
"Readability"= "optimize the readability=\n"
"Fix Grammar"= "fix the grammar of the following text:\n"
"More Idiomatic"= "rewrite in a more idiomatic style:\n"
"Explain Phrase"= "explain the phrase:\n"
"Alternative Words"= "name alternative words for:\n"
"Opposite"= "name the opposite of:\n"
"Typical Sentence"= "write a typical sentence with:\n"
"Facts" = "A list of the main facts of the following text is:\n1)"

# Startup props are used during startup and cannot be overwritten by custom profiles
[startup]
# let the companion be always on top; very useful for working inside large texts
on_top = 0
# The pynput module may have trouble with <ctrl> and <alt> on MacOS. Use <cmd> and <shift> instead if
# you experience any difficulties. <alt> on the Mac is equivalent to the "Option" key.
hotkey = '<ctrl>+<alt>+g'
hotkey2 = '<ctrl>+<alt>+f'
# Apps have to digest the hotkeys first before they can copy selected text. This takes a little time.
# After the waiting time the companion sends ctr+c (macOS cmd+c) to the app.
# If you notice that selected text is not copied or a "c" overwrites the text, try increasing the time.
hotkey_wait = 1.5  # seconds
# 1 = call GPT immediately after pasting the text, 0 = off
autocall = 1
# 1 = display in-place action popup after hot key has been pressed, 0 = off
action_popup = 1
# font size for all the things
font_size = 12
