# GPT Companion default profile
# Do not change property names in this file. Do not delete any property.
# To reduce redundancy, custom profiles overwrite the defaults.
#
[settings]
# MANDATORY in custom profile
name  = "Default"
# OPTIONAL in custom profile
# Model names taken from https://platform.openai.com/playground
models = ['text-davinci-003', 'code-davinci-002']
# OPTIONAL in custom profile
# Unfortunately, the naming of the ChatGPT models give no hint about what they are. However, they require
# a different HTTP endpoint. The companion does not implement a chat. It is using single requests with no history.
chat_models = ['gpt-3.5-turbo-0301', 'gpt-3.5-turbo']
# OPTIONAL in custom profile: Chat models have a 'system' role, which gives a general instruction to the model.
chat_instruction = "be precise and concise"

# key-value pairs of action names, which are displayed as choices in the UI, and action prompts, which are put in front
# of the input text. The first entry is the default.
# MANDATORY in custom model
[actions]
"Pass-through"= ""
"Summarize" =  "rewrite summarized:\n"
"Readability"= "optimize the readability=\n"
"Fix Grammar"= "fix the grammar of the following text:\n"
"More idiomatic"= "rewrite in a more idiomatic style:\n"
"Explain Word"= "explain the word "
"Alternative Words"= "name alternative words for:\n"
"Opposite"= "name the opposite of:\n"
"Typical Sentence"= "write a typical sentence with:\n"

# The following props are only used during startup and cannot be overwritten by custom profiles
[startup]
# let the companion be always on top; very useful for working inside large texts
on_top = 0
# GPT temperature
temperature = 0.7
# default value for max number of tokens in response
max_tokens = 500
# start value of the corresponding checkbox in the UI. 1 = call GPT immediately after pasting the text
autocall = 1
# enable/disable in-place action popup after hot key has been pressed
action_popup = 1

# The pynput module may have trouble with <ctrl> and <alt> on MacOS. Use <cmd> and <shift> instead.
# hotkey = '<cmd>+<shift>+g'
hotkey = '<ctrl>+<alt>+g'
# Apps have to digest the hotkeys first before they can copy selected text. This takes a little time.
# After the waiting time the companion sends COPY_KEY keypress to the app.
# If you notice that selected text is not copied, try increasing the time or use another hotkey.
hotkey_wait = 1  # seconds
